classdef NeuronTest < matlab.unittest.TestCase
% NEURONTEST
%
% Description:
%   Long overdue testing framework. Work in progress
%
% History:
%   30Mar2018 - SSP
% -------------------------------------------------------------------------

	properties
		T1 % Test Neuron 1
		T2 % Test Neuron, 2 equally sized annotations
		PR % Closed curve only 
	end

	methods (TestClassSetup)
		function createNeuron(tc)
			tc.PR = Neuron(2542, 'i');
			tc.T1 = Neuron(7161, 'i');
			tc.T2 = Neuron(7162, 'i');
		end
	end

	methods (Test)
		function testSomaSize(testCase)
			import matlab.unittest.constraints.HasElementCount;

			% Radius
			testCase.verifyEqual(...
				testCase.T1.getSomaSize(),...
				max(testCase.T1.nodes.Rum),...
				'Soma radius calculation incorrect');
			% Diameter
			testCase.verifyEqual(...
				testCase.T1.getSomaSize(true),...
				2*max(testCase.T1.nodes.Rum),...
				'Soma diameter calculation incorrect');
			% Cone pedicle (disc approximation of closed curve)
			testCase.verifyEqual(...
				testCase.PR.getSomaSize(),...
				max(testCase.PR.nodes.Rum),...
				'Closed curve soma calculation is incorrect');
			% Multiple soma nodes
			testCase.verifyThat(...
				testCase.T2.getSomaSize(),...
				HasElementCount(1),...
				'More than one soma node returned');
			% Import accuracy
			testCase.verifyEqual(...
				max(testCase.T1.nodes.Radius), 851.79,...
				'AbsTol', 0.01,...
				'Soma size for T1 is incorrect');
		end

		function testSomaID(testCase)
			import matlab.unittest.constraints.HasElementCount;

			testCase.verifyEqual(...
				testCase.T1.getSomaID(), 176264,...
				'Soma ID incorrect');
			testCase.verifyThat(...
				testCase.T2.getSomaID(),...
				HasElementCount(1));
            % TODO: Check clipboard success
        end
        
        function testSomaXYZ(testCase)
            import matlab.unittest.constraints.HasElementCount;
            
            % Import accuracy
            xyz = testCase.T1.getSomaXYZ(false); % unit = pixels
            testCase.verifyEqual(...
            	xyz(1), 7227.79, 'AbsTol', 0.01,...
            	'Soma X value (pixels) is incorrect');
            testCase.verifyEqual(...
            	xyz(2), 1172.65, 'AbsTol', 0.01,...
            	'Soma Y value (pixels) is incorrect');
            testCase.verifyEqual(...
            	xyz(3), 490,...
            	'Soma Z section (number) is incorrect');

            % Correct number for multiple max node case
            testCase.verifyThat(...
                testCase.T2.getSomaXYZ(),...
                HasElementCount(3));         
        end

        function testCellXYZ(testCase)
        	import matlab.unittest.constraints.HasSize;

        	testCase.verifyThat(...
        		testCase.T2.getCellXYZ(),...
        		HasSize([2 3]),...
        		'Cell XYZ size is incorrect');
        end
        
        function testDAspect(testCase)
            testCase.verifyEqual(...
                testCase.T1.getDAspect(), [0.0833 0.0833 1],...
                'AbsTol', 0.01,...
                'XYZ dimensions are incorrect');
        end
	end
end